<?xml version="1.0" encoding="UTF-8"?><testrun name="Rerun server.ServerUnitTests" project="Record_Indexer" tests="6" started="0" failures="0" errors="1" ignored="0">
  <testsuite name="server.ServerUnitTests" incomplete="true">
    <error>java.lang.Exception: Unable to deal with the IOException thrown: Source '../../../Records' does not exist
	at shared.DataImporter.importData(DataImporter.java:56)
	at server.ServerUnitTests.setUpBeforeClass(ServerUnitTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.io.FileNotFoundException: Source '../../../Records' does not exist
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230)
	at shared.DataImporter.importData(DataImporter.java:48)
	... 16 more

</error>
    <testcase name="validateUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="invalidUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="invalidInputUserTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getProjectsTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getProjectsInvalidTest" classname="server.ServerUnitTests" incomplete="true"/>
    <testcase name="getSampleImageTest" classname="server.ServerUnitTests" incomplete="true"/>
  </testsuite>
</testrun>
